# ============================================
# BDFut Prometheus Configuration
# ============================================
"""
Configuração do Prometheus para monitoramento do sistema BDFut.
Define targets de scraping, regras de alerta e configurações globais.
"""

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'bdfut-cluster'
    environment: 'development'

# Configuração de regras de alerta
rule_files:
  - "rules/*.yml"

# Configuração de alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Configuração de scraping
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # BDFut Application
  - job_name: 'bdfut-app'
    static_configs:
      - targets: ['bdfut-app:8000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true

  # BDFut Worker
  - job_name: 'bdfut-worker'
    static_configs:
      - targets: ['bdfut-worker:8001']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s
    metrics_path: /metrics

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    metrics_path: /metrics

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # Jaeger
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 30s
    metrics_path: /metrics

  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s
    metrics_path: /metrics